image: docker

branches:
  - master

deploy:
  - docker login reg.merlin.gg -u $REG_USER -p $REG_PASSWD
  - docker build -t reg.merlin.gg/embed-generator:$ABSTRUSE_BRANCH .
  - docker push reg.merlin.gg/embed-generator:$ABSTRUSE_BRANCH