apiVersion: apps/v1
kind: Deployment
metadata:
  name: embed-generator
  labels:
    app: embed-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: embed-generator
  template:
    metadata:
      labels:
        app: embed-generator
    spec:
      containers:
      - name: embed-generator
        image: r.cfcr.io/{{CF_ACCOUNT}}/{{CF_REPO_NAME}}:{{CF_SHORT_REVISION}}
        resources:
            limits:
                memory: 3Gi
            requests:
                memory: 2Gi
        envFrom:
        - configMapRef:
            name: embed-generator
      imagePullSecrets:
      - name: regcred